GSLAM: XMLNode Class Reference
XMLNode Class Reference abstract
#include <XML.h>
Public Member Functions
const XMLDocument * GetDocument () const
XMLDocument * GetDocument ()
virtual XMLElement * ToElement ()
virtual XMLText * ToText ()
virtual XMLComment * ToComment ()
virtual XMLDocument * ToDocument ()
virtual XMLDeclaration * ToDeclaration ()
virtual XMLUnknown * ToUnknown ()
virtual const XMLElement * ToElement () const
virtual const XMLText * ToText () const
virtual const XMLComment * ToComment () const
virtual const XMLDocument * ToDocument () const
virtual const XMLDeclaration * ToDeclaration () const
virtual const XMLUnknown * ToUnknown () const
const char * Value () const
void SetValue (const char *val, bool staticMem=false)
int GetLineNum () const
const XMLNode * Parent () const
XMLNode * Parent ()
bool NoChildren () const
const XMLNode * FirstChild () const
XMLNode * FirstChild ()
const XMLElement * FirstChildElement (const char *name=0) const
XMLElement * FirstChildElement (const char *name=0)
const XMLNode * LastChild () const
XMLNode * LastChild ()
const XMLElement * LastChildElement (const char *name=0) const
XMLElement * LastChildElement (const char *name=0)
const XMLNode * PreviousSibling () const
XMLNode * PreviousSibling ()
const XMLElement * PreviousSiblingElement (const char *name=0) const
XMLElement * PreviousSiblingElement (const char *name=0)
const XMLNode * NextSibling () const
XMLNode * NextSibling ()
const XMLElement * NextSiblingElement (const char *name=0) const
XMLElement * NextSiblingElement (const char *name=0)
XMLNode * InsertEndChild (XMLNode *addThis)
XMLNode * LinkEndChild (XMLNode *addThis)
XMLNode * InsertFirstChild (XMLNode *addThis)
XMLNode * InsertAfterChild (XMLNode *afterThis, XMLNode *addThis)
void DeleteChildren ()
void DeleteChild (XMLNode *node)
virtual XMLNode * ShallowClone (XMLDocument *document) const =0
virtual bool ShallowEqual (const XMLNode *compare) const =0
virtual bool Accept (XMLVisitor *visitor) const =0
void SetUserData (void *userData)
void * GetUserData () const
Protected Member Functions
XMLNode (XMLDocument *)
virtual char * ParseDeep (char *, StrPair *, int *)
Protected Attributes
XMLDocument * _document
XMLNode * _parent
StrPair _value
int _parseLineNum
XMLNode * _firstChild
XMLNode * _lastChild
XMLNode * _prev
XMLNode * _next
void * _userData
Detailed Description
XMLNode is a base class for every object that is in the XML Document Object Model (DOM), except XMLAttributes.
Nodes have siblings, a parent, and children which can be navigated. A node is always in a XMLDocument. The type of a XMLNode can be queried, and it can be cast to its more defined type.
A XMLDocument allocates memory for all its Nodes. When the XMLDocument gets deleted, all its Nodes will also be deleted.
A Document can contain: Element (container or leaf)
                        Comment (leaf)
                        Unknown (leaf)
                        Declaration( leaf )
An Element can contain: Element (container or leaf)
                        Text    (leaf)
                        Attributes (not on tree)
                        Comment (leaf)
                        Unknown (leaf)
Member Function Documentation
const char * Value () const
The meaning of 'value' changes for the specific type.
Document:   empty (NULL is returned, not an empty string)
Element:    name of the element
Comment:    the comment text
Unknown:    the tag contents
Text:       the text string
References XMLNode::ToDocument().
Referenced by XMLElement::GetText(), XMLElement::QueryBoolText(), XMLElement::QueryDoubleText(), XMLElement::QueryFloatText(), XMLElement::QueryInt64Text(), XMLElement::QueryIntText(), XMLElement::QueryUnsignedText(), XMLText::ShallowClone(), XMLComment::ShallowClone(), XMLDeclaration::ShallowClone(), XMLUnknown::ShallowClone(), XMLElement::ShallowClone(), XMLText::ShallowEqual(), XMLComment::ShallowEqual(), XMLDeclaration::ShallowEqual(), XMLUnknown::ShallowEqual(), and XMLPrinter::Visit().
void SetValue (const char * val, bool staticMem = false)
Set the Value of an XML node.
See Also
Value()
Referenced by XMLElement::SetText().
XMLNode * InsertEndChild (XMLNode * addThis)
Add a child node as the last (right) child.
If the child node is already part of the document, it is moved from its old location to the new location. Returns the addThis argument or 0 if the node does not belong to the same document.
Referenced by XMLNode::InsertAfterChild().
XMLNode * InsertFirstChild (XMLNode * addThis)
Add a child node as the first (left) child.
If the child node is already part of the document, it is moved from its old location to the new location. Returns the addThis argument or 0 if the node does not belong to the same document.
Referenced by XMLElement::SetText().
XMLNode * InsertAfterChild (XMLNode * afterThis, XMLNode * addThis)
Add a node after the specified child node.
If the child node is already part of the document, it is moved from its old location to the new location. Returns the addThis argument or 0 if the afterThis node is not a child of this node, or if the node does not belong to the same document.
References XMLNode::InsertEndChild().
virtual XMLNode* ShallowClone (XMLDocument * document) const pure virtual
Make a copy of this node, but not its children.
You may pass in a Document pointer that will be the owner of the new Node. If the 'document' is null, then the node returned will be allocated from the current Document. (this->GetDocument())
Note: if called on a XMLDocument, this will return null.
Implemented in XMLDocument, XMLElement, XMLUnknown, XMLDeclaration, XMLComment, and XMLText.
virtual bool ShallowEqual (const XMLNode * compare) const pure virtual
Test if 2 nodes are the same, but don't test children.
The 2 nodes do not need to be in the same Document.
Note: if called on a XMLDocument, this will return false.
Implemented in XMLDocument, XMLElement, XMLUnknown, XMLDeclaration, XMLComment, and XMLText.
virtual bool Accept (XMLVisitor * visitor) const pure virtual
Accept a hierarchical visit of the nodes in the TinyXML-2 DOM.
Every node in the XML tree will be conditionally visited and the host will be called back via the XMLVisitor interface.
This is essentially a SAX interface for TinyXML-2. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML-2 is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
http://www.saxproject.org/
http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for "visiting".
An example of using Accept():
XMLPrinter printer;
tinyxmlDoc.Accept(&printer);
const char* xmlcstr = printer.CStr();
Implemented in XMLDocument, XMLElement, XMLUnknown, XMLDeclaration, XMLComment, and XMLText.
void SetUserData (void * userData)
Set user data into the XMLNode.
TinyXML-2 in no way processes or interprets user data. It is initially 0.
void* GetUserData () const
Get user data set into the XMLNode.
TinyXML-2 in no way processes or interprets user data. It is initially 0.