GSLAM: GPSConverter Class Reference
GPSConverter Class Reference
Public Types
typedef PointWithLatLng Gps
Static Public Member Functions
static Gps gps84_To_Gcj02 (double lat, double lon)
static Gps gcj_To_Gps84 (double lat, double lon)
static Gps gcj02_To_Bd09 (double gg_lat, double gg_lon)
static Gps bd09_To_Gcj02 (double bd_lat, double bd_lon)
static Gps bd09_To_Gps84 (double bd_lat, double bd_lon)
static Gps gps84_To_Bd09 (double lat, double lon)
static bool outOfChina (double lat, double lon)
static Gps transform (double lat, double lon)
static double transformLat (double x, double y)
static double transformLon (double x, double y)
Static Public Attributes
constexpr static const double pi = 3.1415926535897932384626
constexpr static const double a = 6378245.0
constexpr static const double ee = 0.00669342162296594323
Member Function Documentation
static Gps gps84_To_Gcj02 (double lat, double lon) static
84 to 火星坐标系 (GCJ-02) World Geodetic System ==> Mars Geodetic System
Parameters
lat
lon
Returns
Referenced by GCJ02Projection::fromLatLngToPixel().
static Gps gcj_To_Gps84 (double lat, double lon) static
火星坐标系 (GCJ-02) to 84 * *
Parameters
lon *
lat *
Returns
Referenced by GPSConverter::bd09_To_Gps84(), and GCJ02Projection::fromPixelToLatLng().
static Gps gcj02_To_Bd09 (double gg_lat, double gg_lon) static
火星坐标系 (GCJ-02) 与百度坐标系 (BD-09) 的转换算法 将 GCJ-02 坐标转换成 BD-09 坐标
Parameters
gg_lat
gg_lon
static Gps bd09_To_Gcj02 (double bd_lat, double bd_lon) static
火星坐标系 (GCJ-02) 与百度坐标系 (BD-09) 的转换算法 * * 将 BD-09 坐标转换成GCJ-02 坐标 * *
Parameters
bd_lat *
bd_lon *
Returns
Referenced by GPSConverter::bd09_To_Gps84().
static Gps bd09_To_Gps84 (double bd_lat, double bd_lon) static
(BD-09)–>84
Parameters
bd_lat
bd_lon
Returns
References GPSConverter::bd09_To_Gcj02(), and GPSConverter::gcj_To_Gps84().