GSLAM: XMLDeclaration Class Reference
XMLDeclaration Class Reference
#include <XML.h>
Public Member Functions
virtual XMLDeclaration * ToDeclaration ()
virtual const XMLDeclaration * ToDeclaration () const
virtual bool Accept (XMLVisitor *visitor) const
virtual XMLNode * ShallowClone (XMLDocument *document) const
virtual bool ShallowEqual (const XMLNode *compare) const
Public Member Functions inherited from XMLNode
const XMLDocument * GetDocument () const
XMLDocument * GetDocument ()
virtual XMLElement * ToElement ()
virtual XMLText * ToText ()
virtual XMLComment * ToComment ()
virtual XMLDocument * ToDocument ()
virtual XMLUnknown * ToUnknown ()
virtual const XMLElement * ToElement () const
virtual const XMLText * ToText () const
virtual const XMLComment * ToComment () const
virtual const XMLDocument * ToDocument () const
virtual const XMLUnknown * ToUnknown () const
const char * Value () const
void SetValue (const char *val, bool staticMem=false)
int GetLineNum () const
const XMLNode * Parent () const
XMLNode * Parent ()
bool NoChildren () const
const XMLNode * FirstChild () const
XMLNode * FirstChild ()
const XMLElement * FirstChildElement (const char *name=0) const
XMLElement * FirstChildElement (const char *name=0)
const XMLNode * LastChild () const
XMLNode * LastChild ()
const XMLElement * LastChildElement (const char *name=0) const
XMLElement * LastChildElement (const char *name=0)
const XMLNode * PreviousSibling () const
XMLNode * PreviousSibling ()
const XMLElement * PreviousSiblingElement (const char *name=0) const
XMLElement * PreviousSiblingElement (const char *name=0)
const XMLNode * NextSibling () const
XMLNode * NextSibling ()
const XMLElement * NextSiblingElement (const char *name=0) const
XMLElement * NextSiblingElement (const char *name=0)
XMLNode * InsertEndChild (XMLNode *addThis)
XMLNode * LinkEndChild (XMLNode *addThis)
XMLNode * InsertFirstChild (XMLNode *addThis)
XMLNode * InsertAfterChild (XMLNode *afterThis, XMLNode *addThis)
void DeleteChildren ()
void DeleteChild (XMLNode *node)
void SetUserData (void *userData)
void * GetUserData () const
Protected Member Functions
XMLDeclaration (XMLDocument *doc)
char * ParseDeep (char *, StrPair *endTag, int *curLineNumPtr)
Protected Member Functions inherited from XMLNode
XMLNode (XMLDocument *)
Additional Inherited Members
Protected Attributes inherited from XMLNode
XMLDocument * _document
XMLNode * _parent
StrPair _value
int _parseLineNum
XMLNode * _firstChild
XMLNode * _lastChild
XMLNode * _prev
XMLNode * _next
void * _userData
Detailed Description
In correct XML the declaration is the first entry in the file.
    <?xml version="1.0" standalone="yes"?>
TinyXML-2 will happily read or write files without a declaration, however.
The text of the declaration isn't interpreted. It is parsed and written as a string.
Member Function Documentation
bool Accept (XMLVisitor * visitor) const virtual
Accept a hierarchical visit of the nodes in the TinyXML-2 DOM.
Every node in the XML tree will be conditionally visited and the host will be called back via the XMLVisitor interface.
This is essentially a SAX interface for TinyXML-2. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML-2 is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
http://www.saxproject.org/
http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for "visiting".
An example of using Accept():
XMLPrinter printer;
tinyxmlDoc.Accept(&printer);
const char* xmlcstr = printer.CStr();
Implements XMLNode.
References XMLVisitor::Visit().
XMLNode * ShallowClone (XMLDocument * document) const virtual
Make a copy of this node, but not its children.
You may pass in a Document pointer that will be the owner of the new Node. If the 'document' is null, then the node returned will be allocated from the current Document. (this->GetDocument())
Note: if called on a XMLDocument, this will return null.
Implements XMLNode.
References XMLDocument::NewDeclaration(), and XMLNode::Value().
bool ShallowEqual (const XMLNode * compare) const virtual
Test if 2 nodes are the same, but don't test children.
The 2 nodes do not need to be in the same Document.
Note: if called on a XMLDocument, this will return false.
Implements XMLNode.
References XMLNode::ToDeclaration(), and XMLNode::Value().