GSLAM: PureProjection Class Reference
PureProjection Class Reference abstract
Public Member Functions
virtual std::string type ()
virtual double axis () const =0
virtual double flattening () const =0
virtual Size tileSize () const =0
virtual Point2i fromLatLngToPixel (double lat, double lng, int zoom)=0
Point2i fromLatLngToPixel (const PointWithLatLng &p, int zoom)
virtual Point2i fromLatLngToTileXY (double lat, double lng, int zoom)=0
Point2i fromLatLngToTileXY (const PointWithLatLng &p, int zoom)
virtual PointWithLatLng fromPixelToLatLng (int x, int y, int zoom)=0
PointWithLatLng fromPixelToLatLng (const Point2i &p, int zoom)
virtual Point2i fromPixelToTileXY (const Point2i &p)
virtual Point2i fromTileXYToPixel (const Point2i &p)
virtual Size getTileMatrixMinXY (int zoom)=0
virtual Size getTileMatrixMaxXY (int zoom)=0
virtual Size getTileMatrixSizeXY (int zoom)
int getTileMatrixItemCount (int zoom)
virtual Size getTileMatrixSizePixel (int zoom)
virtual double getGroundResolution (int zoom, const double &latitude)
virtual int getBestZoom (const double &gsd, const double &lat)
double degreesToRadians (const double &deg) const
double radiansToDegrees (const double &rad) const
void fromGeodeticToCartesian (double Lat, double Lng, double Height, double &X, double &Y, double &Z)
void fromCartesianTGeodetic (const double &X, const double &Y, const double &Z, double &Lat, double &Lng)
virtual int zoomMax (void) const
Public Member Functions inherited from GObject
virtual std::string type () const
virtual void call (const std::string &command, void *arg=NULL)
virtual void draw ()
virtual bool toByteArray (std::vector< uchar > &array)
virtual bool fromByteArray (std::vector< uchar > &array)
Static Public Member Functions
static double distanceBetweenLatLng (PointWithLatLng const &p1, PointWithLatLng const &p2)
Static Protected Member Functions
static double sign (const double &x)
static double adjustLongitude (double x)
static void SinCos (const double &val, double &sin, double &cos)
static double e0fn (const double &x)
static double e1fn (const double &x)
static double e2fn (const double &x)
static double e3fn (const double &x)
static double mlfn (const double &e0, const double &e1, const double &e2, const double &e3, const double &phi)
static int64_t getUTMzone (const double &lon)
Static Protected Attributes
static constexpr const double PI = M_PI
static constexpr const double HALF_PI = (M_PI * 0.5)
static constexpr const double TWO_PI = (M_PI * 2.0)
static constexpr const double EPSLoN = 1.0e-10
static constexpr const double MAX_VAL = 4
static constexpr const double maxLong = 2147483647
static constexpr const double DBLLONG = 4.61168601e18
static constexpr const double R2D =180.0/M_PI
static constexpr const double D2R =M_PI/180.0
static constexpr const int ZOOMMAX = 22
Member Function Documentation
virtual double axis () const pure virtual
axis of earth (radius of earth)
Returns
radius of earth
Implemented in MercatorProjection.
virtual double flattening () const pure virtual
flattening coefficient of earth
Returns
flattening coefficient
Implemented in MercatorProjection.
virtual Size tileSize () const pure virtual
Get one tile's size (in pixel)
Returns
usually (256,256)
Implemented in MercatorProjection.
Referenced by PureProjection::fromPixelToTileXY(), and PureProjection::fromTileXYToPixel().
virtual Point2i fromLatLngToPixel (double lat, double lng, int zoom) pure virtual
Get pixel position from lat/lng.
Parameters
lat - latitude (y-axis)
lng - longtitude (x-axis)
zoom - zoom level
Returns
pixel position of given lat/lng position
Implemented in GCJ02Projection, and MercatorProjection.
Referenced by PureProjection::fromLatLngToPixel().
Point2i fromLatLngToPixel (const PointWithLatLng & p, int zoom)
Get pixel position from lat/lng.
Parameters
p - lng(x) / lat(y)
zoom - zoom level
Returns
pixel position of given lat/lng position
References PureProjection::fromLatLngToPixel().
virtual Point2i fromLatLngToTileXY (double lat, double lng, int zoom) pure virtual
Get tile index from given lat/lng values.
Parameters
lat - latitude (y-axis)
lng - longitude (x-axis)
zoom - zoom level
Returns
tile index
Implemented in MercatorProjection.
virtual PointWithLatLng fromPixelToLatLng (int x, int y, int zoom) pure virtual
Get lat/lng from pixel position.
Parameters
x - pixel position (x)
y - pixel position (y)
zoom - zoom level
Returns
current lng(x)/lat(y) position
Implemented in GCJ02Projection, and MercatorProjection.
Referenced by PureProjection::fromPixelToLatLng().
PointWithLatLng fromPixelToLatLng (const Point2i & p, int zoom)
Get lat/lng from pixel position.
Parameters
p - pixel position
zoom - zoom level
Returns
current lng(x)/lat(y) position
References PureProjection::fromPixelToLatLng().
virtual Point2i fromPixelToTileXY (const Point2i & p) virtual
Get tile index from pixel position.
Parameters
p - pixel position
Returns
current active tile position
References PureProjection::tileSize().
virtual Point2i fromTileXYToPixel (const Point2i & p) virtual
Get pixel position from current tile index.
Parameters
p - tile index
Returns
current tile's pixel position
References PureProjection::tileSize().
int zoomMax (void) const virtual
Get maximum zoom level.
Returns
maximum zoom level (default is 23)