GSLAM: XMLElement Class Reference
XMLElement Class Reference
#include <XML.h>
Public Types
enum { OPEN, CLOSED, CLOSING }
Public Member Functions
const char * Name () const
void SetName (const char *str, bool staticMem=false)
virtual XMLElement * ToElement ()
virtual const XMLElement * ToElement () const
virtual bool Accept (XMLVisitor *visitor) const
const char * Attribute (const char *name, const char *value=0) const
int IntAttribute (const char *name, int defaultValue=0) const
unsigned UnsignedAttribute (const char *name, unsigned defaultValue=0) const
int64_t Int64Attribute (const char *name, int64_t defaultValue=0) const
bool BoolAttribute (const char *name, bool defaultValue=false) const
double DoubleAttribute (const char *name, double defaultValue=0) const
float FloatAttribute (const char *name, float defaultValue=0) const
XMLError QueryIntAttribute (const char *name, int *value) const
XMLError QueryUnsignedAttribute (const char *name, unsigned int *value) const
XMLError QueryInt64Attribute (const char *name, int64_t *value) const
XMLError QueryBoolAttribute (const char *name, bool *value) const
XMLError QueryDoubleAttribute (const char *name, double *value) const
XMLError QueryFloatAttribute (const char *name, float *value) const
int QueryAttribute (const char *name, int *value) const
int QueryAttribute (const char *name, unsigned int *value) const
int QueryAttribute (const char *name, int64_t *value) const
int QueryAttribute (const char *name, bool *value) const
int QueryAttribute (const char *name, double *value) const
int QueryAttribute (const char *name, float *value) const
void SetAttribute (const char *name, const char *value)
void SetAttribute (const char *name, int value)
void SetAttribute (const char *name, unsigned value)
void SetAttribute (const char *name, int64_t value)
void SetAttribute (const char *name, bool value)
void SetAttribute (const char *name, double value)
void SetAttribute (const char *name, float value)
void DeleteAttribute (const char *name)
const XMLAttribute * FirstAttribute () const
const XMLAttribute * FindAttribute (const char *name) const
const char * GetText () const
void SetText (const char *inText)
void SetText (int value)
void SetText (unsigned value)
void SetText (int64_t value)
void SetText (bool value)
void SetText (double value)
void SetText (float value)
XMLError QueryIntText (int *ival) const
XMLError QueryUnsignedText (unsigned *uval) const
XMLError QueryInt64Text (int64_t *uval) const
XMLError QueryBoolText (bool *bval) const
XMLError QueryDoubleText (double *dval) const
XMLError QueryFloatText (float *fval) const
int IntText (int defaultValue=0) const
unsigned UnsignedText (unsigned defaultValue=0) const
int64_t Int64Text (int64_t defaultValue=0) const
bool BoolText (bool defaultValue=false) const
double DoubleText (double defaultValue=0) const
float FloatText (float defaultValue=0) const
int ClosingType () const
virtual XMLNode * ShallowClone (XMLDocument *document) const
virtual bool ShallowEqual (const XMLNode *compare) const
Public Member Functions inherited from XMLNode
const XMLDocument * GetDocument () const
XMLDocument * GetDocument ()
virtual XMLText * ToText ()
virtual XMLComment * ToComment ()
virtual XMLDocument * ToDocument ()
virtual XMLDeclaration * ToDeclaration ()
virtual XMLUnknown * ToUnknown ()
virtual const XMLText * ToText () const
virtual const XMLComment * ToComment () const
virtual const XMLDocument * ToDocument () const
virtual const XMLDeclaration * ToDeclaration () const
virtual const XMLUnknown * ToUnknown () const
const char * Value () const
void SetValue (const char *val, bool staticMem=false)
int GetLineNum () const
const XMLNode * Parent () const
XMLNode * Parent ()
bool NoChildren () const
const XMLNode * FirstChild () const
XMLNode * FirstChild ()
const XMLElement * FirstChildElement (const char *name=0) const
XMLElement * FirstChildElement (const char *name=0)
const XMLNode * LastChild () const
XMLNode * LastChild ()
const XMLElement * LastChildElement (const char *name=0) const
XMLElement * LastChildElement (const char *name=0)
const XMLNode * PreviousSibling () const
XMLNode * PreviousSibling ()
const XMLElement * PreviousSiblingElement (const char *name=0) const
XMLElement * PreviousSiblingElement (const char *name=0)
const XMLNode * NextSibling () const
XMLNode * NextSibling ()
const XMLElement * NextSiblingElement (const char *name=0) const
XMLElement * NextSiblingElement (const char *name=0)
XMLNode * InsertEndChild (XMLNode *addThis)
XMLNode * LinkEndChild (XMLNode *addThis)
XMLNode * InsertFirstChild (XMLNode *addThis)
XMLNode * InsertAfterChild (XMLNode *afterThis, XMLNode *addThis)
void DeleteChildren ()
void DeleteChild (XMLNode *node)
void SetUserData (void *userData)
void * GetUserData () const
Protected Member Functions
char * ParseDeep (char *p, StrPair *endTag, int *curLineNumPtr)
Protected Member Functions inherited from XMLNode
XMLNode (XMLDocument *)
Additional Inherited Members
Protected Attributes inherited from XMLNode
XMLDocument * _document
XMLNode * _parent
StrPair _value
int _parseLineNum
XMLNode * _firstChild
XMLNode * _lastChild
XMLNode * _prev
XMLNode * _next
void * _userData
Detailed Description
The element is a container class.
It has a value, the element name, and can contain other elements, text, comments, and unknowns. Elements also contain an arbitrary number of attributes.
Member Function Documentation
bool Accept (XMLVisitor * visitor) const virtual
Accept a hierarchical visit of the nodes in the TinyXML-2 DOM.
Every node in the XML tree will be conditionally visited and the host will be called back via the XMLVisitor interface.
This is essentially a SAX interface for TinyXML-2. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML-2 is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
http://www.saxproject.org/
http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for "visiting".
An example of using Accept():
XMLPrinter printer;
tinyxmlDoc.Accept(&printer);
const char* xmlcstr = printer.CStr();
Implements XMLNode.
References XMLNode::FirstChild(), XMLNode::NextSibling(), XMLVisitor::VisitEnter(), and XMLVisitor::VisitExit().
const char * Attribute (const char * name, const char * value = 0) const
Given an attribute name, Attribute() returns the value for the attribute of that name, or null if none exists.
For example:
const char* value = ele->Attribute("foo");
The 'value' parameter is normally null. However, if specified, the attribute will only be returned if the 'name' and 'value' match. This allow you to write code:
if (ele->Attribute("foo", "bar")) callFooIsBar();
rather than:
if (ele->Attribute("foo")) {
    if ( strcmp( ele->Attribute( "foo" ), "bar" ) == 0 ) callFooIsBar();
}
References XMLElement::FindAttribute(), and XMLAttribute::Value().
int IntAttribute (const char * name, int defaultValue = 0) const
Given an attribute name, IntAttribute() returns the value of the attribute interpreted as an integer.
The default value will be returned if the attribute isn't present, or if there is an error. (For a method with error checking, see QueryIntAttribute()).
References XMLElement::QueryIntAttribute().
XMLError QueryIntAttribute (const char * name, int * value) const
Given an attribute name, QueryIntAttribute() returns XML_SUCCESS, XML_WRONG_ATTRIBUTE_TYPE if the conversion can't be performed, or XML_NO_ATTRIBUTE if the attribute doesn't exist.
If successful, the result of the conversion will be written to 'value'. If not successful, nothing will be written to 'value'. This allows you to provide default value:
int value = 10;
QueryIntAttribute("foo", &value);     // if "foo" isn't found, value will still be 10
References XMLAttribute::QueryIntValue().
Referenced by XMLElement::IntAttribute().
int QueryAttribute (const char * name, int * value) const
Given an attribute name, QueryAttribute() returns XML_SUCCESS, XML_WRONG_ATTRIBUTE_TYPE if the conversion can't be performed, or XML_NO_ATTRIBUTE if the attribute doesn't exist.
It is overloaded for the primitive types, and is a generally more convenient replacement of QueryIntAttribute() and related functions.
If successful, the result of the conversion will be written to 'value'. If not successful, nothing will be written to 'value'. This allows you to provide default value:
int value = 10;
QueryAttribute("foo", &value);        // if "foo" isn't found, value will still be 10
const char * GetText () const
Convenience function for easy access to the text inside an element.
Although easy and concise, GetText() is limited compared to getting the XMLText child and accessing it directly.
If the first child of 'this' is a XMLText, the GetText() returns the character string of the Text node, else null is returned.
This is a convenient method for getting the text of simple contained text:
<foo>This is text</foo>
    const char* str = fooElement->GetText();
'str' will be a pointer to "This is text".
Note that this function can be misleading. If the element foo was created from this XML:
    <foo><b>This is text</b></foo>
then the value of str would be null. The first child node isn't a text node, it is another element. From this XML:
    <foo>This is <b>text</b></foo>
GetText() will return "This is ".
References XMLNode::FirstChild(), XMLNode::ToText(), and XMLNode::Value().
void SetText (const char * inText)
Convenience function for easy access to the text inside an element.
Although easy and concise, SetText() is limited compared to creating an XMLText child and mutating it directly.
If the first child of 'this' is a XMLText, SetText() sets its value to the given string, otherwise it will create a first child that is an XMLText.
This is a convenient method for setting the text of simple contained text:
<foo>This is text</foo>
    fooElement->SetText( "Hullaballoo!" );
<foo>Hullaballoo!</foo>
Note that this function can be misleading. If the element foo was created from this XML:
    <foo><b>This is text</b></foo>
then it will not change "This is text", but rather prefix it with a text element:
    <foo>Hullaballoo!<b>This is text</b></foo>
For this XML:
    <foo />
SetText() will generate
    <foo>Hullaballoo!</foo>
References XMLNode::FirstChild(), XMLNode::GetDocument(), XMLNode::InsertFirstChild(), XMLDocument::NewText(), XMLNode::SetValue(), and XMLNode::ToText().
Referenced by XMLElement::SetText().
XMLError QueryIntText (int * ival) const
Convenience method to query the value of a child text node.
This is probably best shown by example. Given you have a document is this form:
    <point>
        <x>1</x>
        <y>1.4</y>
    </point>
The QueryIntText() and similar functions provide a safe and easier way to get to the "value" of x and y.
    int x = 0;
    float y = 0;    // types of x and y are contrived for example
    const XMLElement* xElement = pointElement->FirstChildElement( "x" );
    const XMLElement* yElement = pointElement->FirstChildElement( "y" );
    xElement->QueryIntText( &x );
    yElement->QueryFloatText( &y );
Returns
XML_SUCCESS (0) on success, XML_CAN_NOT_CONVERT_TEXT if the text cannot be converted to the requested type, and XML_NO_TEXT_NODE if there is no child text to query.
References XMLNode::FirstChild(), XMLNode::ToText(), and XMLNode::Value().
XMLNode * ShallowClone (XMLDocument * document) const virtual
Make a copy of this node, but not its children.
You may pass in a Document pointer that will be the owner of the new Node. If the 'document' is null, then the node returned will be allocated from the current Document. (this->GetDocument())
Note: if called on a XMLDocument, this will return null.
Implements XMLNode.
References XMLElement::FirstAttribute(), XMLDocument::NewElement(), XMLAttribute::Next(), XMLElement::SetAttribute(), and XMLNode::Value().
bool ShallowEqual (const XMLNode * compare) const virtual
Test if 2 nodes are the same, but don't test children.
The 2 nodes do not need to be in the same Document.
Note: if called on a XMLDocument, this will return false.
Implements XMLNode.
References XMLElement::FirstAttribute(), XMLElement::Name(), XMLAttribute::Next(), XMLNode::ToElement(), and XMLAttribute::Value().