GSLAM: XMLPrinter Class Reference
XMLPrinter Class Reference
#include <XML.h>
Public Member Functions
XMLPrinter (FILE *file=0, bool compact=false, int depth=0)
void PushHeader (bool writeBOM, bool writeDeclaration)
void OpenElement (const char *name, bool compactMode=false)
void PushAttribute (const char *name, const char *value)
void PushAttribute (const char *name, int value)
void PushAttribute (const char *name, unsigned value)
void PushAttribute (const char *name, int64_t value)
void PushAttribute (const char *name, bool value)
void PushAttribute (const char *name, double value)
virtual void CloseElement (bool compactMode=false)
void PushText (const char *text, bool cdata=false)
void PushText (int value)
void PushText (unsigned value)
void PushText (int64_t value)
void PushText (bool value)
void PushText (float value)
void PushText (double value)
void PushComment (const char *comment)
void PushDeclaration (const char *value)
void PushUnknown (const char *value)
virtual bool VisitEnter (const XMLDocument &)
virtual bool VisitExit (const XMLDocument &)
virtual bool VisitEnter (const XMLElement &element, const XMLAttribute *attribute)
virtual bool VisitExit (const XMLElement &element)
virtual bool Visit (const XMLText &text)
virtual bool Visit (const XMLComment &comment)
virtual bool Visit (const XMLDeclaration &declaration)
virtual bool Visit (const XMLUnknown &unknown)
const char * CStr () const
int CStrSize () const
void ClearBuffer ()
Protected Member Functions
virtual bool CompactMode (const XMLElement &)
virtual void PrintSpace (int depth)
void Print (const char *format,...)
void SealElementIfJustOpened ()
Protected Attributes
bool _elementJustOpened
DynArray< const char *, 10 > _stack
Detailed Description
Printing functionality.
The XMLPrinter gives you more options than the XMLDocument::Print() method.
It can:
Print to memory.
Print to a file you provide.
Print XML without a XMLDocument.
Print to Memory
XMLPrinter printer;
doc.Print(&printer);
SomeFunction(printer.CStr());
Print to a File
You provide the file pointer.
XMLPrinter printer(fp);
doc.Print(&printer);
Print without a XMLDocument
When loading, an XML parser is very useful. However, sometimes when saving, it just gets in the way. The code is often set up for streaming, and constructing the DOM is just overhead.
The Printer supports the streaming case. The following code prints out a trivially simple XML file without ever creating an XML document.
XMLPrinter printer(fp);
printer.OpenElement("foo");
printer.PushAttribute("foo", "bar");
printer.CloseElement();
Constructor & Destructor Documentation
XMLPrinter (FILE * file = 0, bool compact = false, int depth = 0)
Construct the printer.
If the FILE* is specified, this will print to the FILE. Else it will print to memory, and the result is available in CStr(). If 'compact' is set to true, then output is created with only required whitespace and newlines.
Member Function Documentation
void PushHeader (bool writeBOM, bool writeDeclaration)
If streaming, write the BOM and declaration.
Referenced by XMLPrinter::VisitEnter().
void OpenElement (const char * name, bool compactMode = false)
If streaming, start writing an element.
The element must be closed with CloseElement()
References XMLPrinter::PrintSpace().
Referenced by XMLPrinter::VisitEnter().
int CStrSize () const
If in print to memory mode, return the size of the XML file in memory.
(Note the size returned includes the terminating null.)
void PrintSpace (int depth) protected virtual
Prints out the space before an element.
You may override to change the space and tabs used. A PrintSpace() override should call Print().
Referenced by XMLPrinter::CloseElement(), XMLPrinter::OpenElement(), and XMLPrinter::PushComment().