GSLAM: SharedLibrary Class Reference
SharedLibrary Class Reference
#include <SharedLibrary.h>
Public Member Functions
SharedLibrary (const std::string &path)
virtual ~SharedLibrary ()
bool load (const std::string &path, int flags=0)
void unload ()
bool isLoaded () const
bool hasSymbol (const std::string &name)
void * getSymbol (const std::string &name)
const std::string & getPath () const
Static Public Member Functions
static std::string suffix ()
Detailed Description
The SharedLibrary class dynamically loads shared libraries at run-time.
Constructor & Destructor Documentation
virtual ~SharedLibrary () virtual
Creates a SharedLibrary object and loads a library from the given path.
References SharedLibrary::isLoaded().
Member Function Documentation
bool load (const std::string & path, int flags = 0)
Destroys the SharedLibrary.
The actual library remains loaded.
Referenced by SharedLibrary::SharedLibrary().
void unload ()
Loads a shared library from the given path.
Throws a LibraryAlreadyLoadedException if a library has already been loaded. Throws a LibraryLoadException if the library cannot be loaded.
void* getSymbol (const std::string & name)
Returns true iff the loaded library contains a symbol with the given name.
Referenced by SharedLibrary::hasSymbol().
const std::string& getPath () const
Returns the address of the symbol with the given name.
For functions, this is the entry point of the function. Throws a NotFoundException if the symbol does not exist.
static std::string suffix () static
Returns the path of the library, as specified in a call to load() or the constructor.