GSLAM: XMLDocument Class Reference
XMLDocument Class Reference
#include <XML.h>
Public Member Functions
XMLDocument (bool processEntities=true, Whitespace=PRESERVE_WHITESPACE)
virtual XMLDocument * ToDocument ()
virtual const XMLDocument * ToDocument () const
XMLError Parse (const char *xml, size_t nBytes=(size_t)(-1))
XMLError LoadFile (const char *filename)
XMLError LoadFile (FILE *)
XMLError SaveFile (const char *filename, bool compact=false)
XMLError SaveFile (FILE *fp, bool compact=false)
bool ProcessEntities () const
Whitespace WhitespaceMode () const
bool HasBOM () const
void SetBOM (bool useBOM)
XMLElement * RootElement ()
const XMLElement * RootElement () const
void Print (XMLPrinter *streamer=0) const
virtual bool Accept (XMLVisitor *visitor) const
XMLElement * NewElement (const char *name)
XMLComment * NewComment (const char *comment)
XMLText * NewText (const char *text)
XMLDeclaration * NewDeclaration (const char *text=0)
XMLUnknown * NewUnknown (const char *text)
void DeleteNode (XMLNode *node)
void SetError (XMLError error, const char *str1, const char *str2, int lineNum)
void ClearError ()
bool Error () const
XMLError ErrorID () const
const char * ErrorName () const
const char * GetErrorStr1 () const
const char * GetErrorStr2 () const
int GetErrorLineNum () const
void PrintError () const
void Clear ()
char * Identify (char *p, XMLNode **node)
virtual XMLNode * ShallowClone (XMLDocument *) const
virtual bool ShallowEqual (const XMLNode *) const
Public Member Functions inherited from XMLNode
const XMLDocument * GetDocument () const
XMLDocument * GetDocument ()
virtual XMLElement * ToElement ()
virtual XMLText * ToText ()
virtual XMLComment * ToComment ()
virtual XMLDeclaration * ToDeclaration ()
virtual XMLUnknown * ToUnknown ()
virtual const XMLElement * ToElement () const
virtual const XMLText * ToText () const
virtual const XMLComment * ToComment () const
virtual const XMLDeclaration * ToDeclaration () const
virtual const XMLUnknown * ToUnknown () const
const char * Value () const
void SetValue (const char *val, bool staticMem=false)
int GetLineNum () const
const XMLNode * Parent () const
XMLNode * Parent ()
bool NoChildren () const
const XMLNode * FirstChild () const
XMLNode * FirstChild ()
const XMLElement * FirstChildElement (const char *name=0) const
XMLElement * FirstChildElement (const char *name=0)
const XMLNode * LastChild () const
XMLNode * LastChild ()
const XMLElement * LastChildElement (const char *name=0) const
XMLElement * LastChildElement (const char *name=0)
const XMLNode * PreviousSibling () const
XMLNode * PreviousSibling ()
const XMLElement * PreviousSiblingElement (const char *name=0) const
XMLElement * PreviousSiblingElement (const char *name=0)
const XMLNode * NextSibling () const
XMLNode * NextSibling ()
const XMLElement * NextSiblingElement (const char *name=0) const
XMLElement * NextSiblingElement (const char *name=0)
XMLNode * InsertEndChild (XMLNode *addThis)
XMLNode * LinkEndChild (XMLNode *addThis)
XMLNode * InsertFirstChild (XMLNode *addThis)
XMLNode * InsertAfterChild (XMLNode *afterThis, XMLNode *addThis)
void DeleteChildren ()
void DeleteChild (XMLNode *node)
void SetUserData (void *userData)
void * GetUserData () const
Static Public Member Functions
static const char * ErrorIDToName (XMLError errorID)
Additional Inherited Members
Protected Member Functions inherited from XMLNode
XMLNode (XMLDocument *)
virtual char * ParseDeep (char *, StrPair *, int *)
Protected Attributes inherited from XMLNode
XMLDocument * _document
XMLNode * _parent
StrPair _value
int _parseLineNum
XMLNode * _firstChild
XMLNode * _lastChild
XMLNode * _prev
XMLNode * _next
void * _userData
Detailed Description
A Document binds together all the functionality.
It can be saved, loaded, and printed to the screen. All Nodes are connected and allocated to a Document. If the Document is deleted, all its Nodes are also deleted.
Member Function Documentation
XMLError Parse (const char * xml, size_t nBytes = (size_t)(-1))
Parse an XML file from a character string.
Returns XML_SUCCESS (0) on success, or an errorID.
You may optionally pass in the 'nBytes', which is the number of bytes which will be parsed. If not specified, TinyXML-2 will assume 'xml' points to a null terminated string.
References XMLDocument::Clear(), XMLNode::DeleteChildren(), XMLDocument::Error(), and XMLDocument::Parse().
Referenced by XMLDocument::LoadFile(), and XMLDocument::Parse().
XMLError LoadFile (const char * filename)
Load an XML file from disk.
Returns XML_SUCCESS (0) on success, or an errorID.
References XMLDocument::Clear().
XMLError LoadFile (FILE * fp)
Load an XML file from disk.
You are responsible for providing and closing the FILE*.
NOTE: The file should be opened as binary ("rb") not text in order for TinyXML-2 to correctly do newline normalization.
Returns XML_SUCCESS (0) on success, or an errorID.
References XMLDocument::Clear(), and XMLDocument::Parse().
XMLError SaveFile (const char * filename, bool compact = false)
Save the XML file to disk.
Returns XML_SUCCESS (0) on success, or an errorID.
XMLError SaveFile (FILE * fp, bool compact = false)
Save the XML file to disk.
You are responsible for providing and closing the FILE*.
Returns XML_SUCCESS (0) on success, or an errorID.
References XMLDocument::Print().
XMLElement* RootElement ()
Return the root element of DOM.
Equivalent to FirstChildElement(). To get the first node, use FirstChild().
void Print (XMLPrinter * streamer = 0) const
Print the Document.
If the Printer is not provided, it will print to stdout. If you provide Printer, this can print to a file:
XMLPrinter printer(fp);
doc.Print(&printer);
Or you can use a printer to print to memory:
XMLPrinter printer;
doc.Print(&printer);
// printer.CStr() has a const char* to the XML
References XMLDocument::Accept().
Referenced by XMLDocument::SaveFile().
bool Accept (XMLVisitor * visitor) const virtual
Accept a hierarchical visit of the nodes in the TinyXML-2 DOM.
Every node in the XML tree will be conditionally visited and the host will be called back via the XMLVisitor interface.
This is essentially a SAX interface for TinyXML-2. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML-2 is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
http://www.saxproject.org/
http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for "visiting".
An example of using Accept():
XMLPrinter printer;
tinyxmlDoc.Accept(&printer);
const char* xmlcstr = printer.CStr();
Implements XMLNode.
References XMLNode::Accept(), XMLNode::NextSibling(), XMLVisitor::VisitEnter(), and XMLVisitor::VisitExit().
Referenced by XMLDocument::Print().
XMLElement * NewElement (const char * name)
Create a new Element associated with this Document.
The memory for the Element is managed by the Document.
Referenced by XMLElement::ShallowClone().
XMLComment * NewComment (const char * comment)
Create a new Comment associated with this Document.
The memory for the Comment is managed by the Document.
Referenced by XMLComment::ShallowClone().
XMLText * NewText (const char * text)
Create a new Text associated with this Document.
The memory for the Text is managed by the Document.
Referenced by XMLText::ShallowClone().
XMLDeclaration * NewDeclaration (const char * text = 0)
Create a new Declaration associated with this Document.
The memory for the object is managed by the Document.
If the 'text' param is null, the standard declaration is used.:
    <?xml version="1.0" encoding="UTF-8"?>
Referenced by XMLDeclaration::ShallowClone().
XMLUnknown * NewUnknown (const char * text)
Create a new Unknown associated with this Document.
The memory for the object is managed by the Document.
Referenced by XMLUnknown::ShallowClone().
void DeleteNode (XMLNode * node)
Delete a node associated with this document.
It will be unlinked from the DOM.
References XMLNode::DeleteChild().
virtual XMLNode* ShallowClone (XMLDocument * document) const virtual
Make a copy of this node, but not its children.
You may pass in a Document pointer that will be the owner of the new Node. If the 'document' is null, then the node returned will be allocated from the current Document. (this->GetDocument())
Note: if called on a XMLDocument, this will return null.
Implements XMLNode.
virtual bool ShallowEqual (const XMLNode * compare) const virtual
Test if 2 nodes are the same, but don't test children.
The 2 nodes do not need to be in the same Document.
Note: if called on a XMLDocument, this will return false.
Implements XMLNode.