GSLAM: GCJ02Projection Class Reference
GCJ02Projection Class Reference
Public Member Functions
virtual Point2i fromLatLngToPixel (double lat, double lng, int zoom)
virtual PointWithLatLng fromPixelToLatLng (int x, int y, int zoom)
Public Member Functions inherited from MercatorProjection
virtual std::string type ()
virtual Size tileSize () const
virtual double axis () const
virtual double flattening () const
virtual Point2i fromLatLngToTileXY (double lat, double lng, int zoom)
virtual Size getTileMatrixMinXY (int zoom)
virtual Size getTileMatrixMaxXY (int zoom)
Public Member Functions inherited from PureProjection
Point2i fromLatLngToPixel (const PointWithLatLng &p, int zoom)
Point2i fromLatLngToTileXY (const PointWithLatLng &p, int zoom)
PointWithLatLng fromPixelToLatLng (const Point2i &p, int zoom)
virtual Point2i fromPixelToTileXY (const Point2i &p)
virtual Point2i fromTileXYToPixel (const Point2i &p)
virtual Size getTileMatrixSizeXY (int zoom)
int getTileMatrixItemCount (int zoom)
virtual Size getTileMatrixSizePixel (int zoom)
virtual double getGroundResolution (int zoom, const double &latitude)
virtual int getBestZoom (const double &gsd, const double &lat)
double degreesToRadians (const double &deg) const
double radiansToDegrees (const double &rad) const
void fromGeodeticToCartesian (double Lat, double Lng, double Height, double &X, double &Y, double &Z)
void fromCartesianTGeodetic (const double &X, const double &Y, const double &Z, double &Lat, double &Lng)
virtual int zoomMax (void) const
Public Member Functions inherited from GObject
virtual std::string type () const
virtual void call (const std::string &command, void *arg=NULL)
virtual void draw ()
virtual bool toByteArray (std::vector< uchar > &array)
virtual bool fromByteArray (std::vector< uchar > &array)
Additional Inherited Members
Static Public Member Functions inherited from PureProjection
static double distanceBetweenLatLng (PointWithLatLng const &p1, PointWithLatLng const &p2)
Static Protected Member Functions inherited from PureProjection
static double sign (const double &x)
static double adjustLongitude (double x)
static void SinCos (const double &val, double &sin, double &cos)
static double e0fn (const double &x)
static double e1fn (const double &x)
static double e2fn (const double &x)
static double e3fn (const double &x)
static double mlfn (const double &e0, const double &e1, const double &e2, const double &e3, const double &phi)
static int64_t getUTMzone (const double &lon)
Static Protected Attributes inherited from PureProjection
static constexpr const double PI = M_PI
static constexpr const double HALF_PI = (M_PI * 0.5)
static constexpr const double TWO_PI = (M_PI * 2.0)
static constexpr const double EPSLoN = 1.0e-10
static constexpr const double MAX_VAL = 4
static constexpr const double maxLong = 2147483647
static constexpr const double DBLLONG = 4.61168601e18
static constexpr const double R2D =180.0/M_PI
static constexpr const double D2R =M_PI/180.0
static constexpr const int ZOOMMAX = 22
Member Function Documentation
virtual Point2i fromLatLngToPixel (double lat, double lng, int zoom) virtual
Get pixel position from lat/lng.
Parameters
lat - latitude (y-axis)
lng - longtitude (x-axis)
zoom - zoom level
Returns
pixel position of given lat/lng position
Reimplemented from MercatorProjection.
References MercatorProjection::fromLatLngToPixel(), and GPSConverter::gps84_To_Gcj02().
virtual PointWithLatLng fromPixelToLatLng (int x, int y, int zoom) virtual
Get lat/lng from pixel position.
Parameters
x - pixel position (x)
y - pixel position (y)
zoom - zoom level
Returns
current lng(x)/lat(y) position
Reimplemented from MercatorProjection.
References MercatorProjection::fromPixelToLatLng(), and GPSConverter::gcj_To_Gps84().