GSLAM: GSLAM Namespace Reference
GSLAM Namespace Reference
Classes
class CameraImpl
class CameraIdeal
class CameraPinhole
class CameraATAN
class CameraOpenCV
class Camera
class CPUMetric
class Dataset
class DatasetFactory
class Estimator
class Evaluation
class GEvent
class FileResource
class GElement
class GElement< uint8_t >
class GElement< char >
class GElement< int16_t >
class GElement< uint16_t >
class GElement< int32_t >
class GElement< float >
class GElement< double >
struct GImageType
struct UMatData
class GImage
class LogSink
class LogFileSink
class GPS
class GPSArray
class GObject
class GObjectHandle
class MapPoint
class FrameConnection
class MapFrame
struct LoopCandidate
class LoopDetector
class Map
class SLAM
class HashMap
class KeyPoint
class MapFusion
class MemoryMetric
class Subscriber
class Publisher
class Messenger
class Event
class ThreadPool
struct InvDepthEstimation
struct KeyFrameEstimzation
struct BundleEdge
struct SE3Edge
struct SIM3Edge
struct GPSEdge
struct BundleGraph
struct OptimzeConfig
class Optimizer
class Random
class SharedLibrary
class Registry
class SvarWithType
class Svar
struct CallbackInfoStruct
class Scommand
class SvarLanguage
class TileBase
class ImageTile
class TerrainTile
class TerrainTileWithInfo
class TileManager
class Size
class PointWithLatLng
class GPSConverter
class PureProjection
class MercatorProjection
class GCJ02Projection
class BaiduProjection
class TicToc
class Rate
class Timer
class ScopedTimer
class UndistorterImpl
class Undistorter
struct Byte
class FrameMono
class FrameRGBD
class FrameStereo
class FrameMonoGPS
class FrameMonoGPSPYR
class FrameMonoIMU
class Vocabulary
class GeneralScoring
Typedefs
typedef pi::Point2d Point2d
typedef pi::Point3d Point3d
typedef CameraATAN CameraPTAM
typedef CameraATAN CameraANTA
typedef SPtr< Dataset > DatasetPtr
typedef SPtr< Dataset >(* funcCreateDataset)()
typedef SPtr< Estimator >(* funcCreateEstimatorInstance)()
typedef int LogSeverity
typedef std::map< LogSeverity,
LogFileSink * > LogSinkMap
typedef size_t NodeId
typedef size_t WordId
typedef float WordValue
typedef std::map< WordId, float > BowVector
typedef std::map< WordId,
std::vector< unsigned int > > FeatureVector
typedef pi::SO3d SO3
typedef pi::SE3d SE3
typedef pi::SIM3d SIM3
typedef pi::Point2i Point2i
typedef pi::Point3f Point3f
typedef pi::Point2f Point2f
typedef pi::Point3ub Point3ub
typedef pi::Point3d Point3Type
typedef Point3ub ColorType
typedef size_t PointID
typedef size_t FrameID
typedef SPtr< GObject > GObjectPtr
typedef SPtr< MapFrame > FramePtr
typedef SPtr< MapPoint > PointPtr
typedef SPtr< FrameConnection > FrameConnectionPtr
typedef SPtr< Map > MapPtr
typedef SPtr< SLAM > SLAMPtr
typedef std::vector< FramePtr > FrameArray
typedef std::vector< PointPtr > PointArray
typedef std::map
< GSLAM::FrameID,
FrameConnectionPtr > FrameConnectionMap
typedef std::vector< std::pair
< FrameID, size_t > > MapPointObsVec
typedef GSLAM::Point3d CameraAnchor
typedef GSLAM::Point2d IdepthEstimation
typedef GSLAM::SLAMPtr(* funcCreateSLAMInstance)()
typedef std::vector
< LoopCandidate > LoopCandidates
typedef SPtr< LoopDetector > LoopDetectorPtr
typedef std::unordered_map
< PointID, PointPtr > PointMap
typedef std::unordered_map
< FrameID, FramePtr > FrameMap
typedef PointMap::iterator PointIt
typedef FrameMap::iterator FrameIt
typedef PointMap::const_iterator ConstPointIt
typedef FrameMap::const_iterator ConstFrameIt
typedef SPtr< MapFusion > MapFusionPtr
typedef GSLAM::MapFusionPtr(* funcCreateMapFusionInstance)()
typedef std::mutex Mutex
typedef std::mutex MutexRW
typedef std::unique_lock< MutexRW > ReadMutex
typedef std::unique_lock< MutexRW > WriteMutex
typedef SPtr< Optimizer >(* funcCreateOptimizerInstance)()
typedef std::pair
< GSLAM::Point3d, bool > MapPointEstimation
typedef SPtr< Optimizer > OptimizerPtr
typedef Point3_< int > Point3i
typedef pi::SE3< double > SE3d
typedef pi::SE3< float > SE3f
typedef SPtr< SharedLibrary > SharedLibraryPtr
typedef pi::SIM3< double > SIM3d
typedef pi::SIM3< float > SIM3f
typedef pi::SO3< double > SO3d
typedef pi::SO3< float > SO3f
typedef SvarWithType< int > SInt
typedef SvarWithType< double > SDouble
typedef SvarWithType< std::string > SString
typedef void(* CallbackProc)(void *ptr, std::string sCommand, std::string sParams)
typedef std::vector
< CallbackInfoStruct > CallbackVector
typedef SPtr< TileBase > TilePtr
typedef SPtr< ImageTile > ImageTilePtr
typedef SPtr< TerrainTile > TerrainTilePtr
typedef SPtr< TerrainTileWithInfo > TerrainTileWithInfoPtr
typedef SPtr< TileManager > TileManagerPtr
typedef SPtr< PureProjection > TileProjectionPtr
typedef SPtr< MercatorProjection > MecatorProjectionPtr
typedef SPtr< GCJ02Projection > GCJ02ProjectionPtr
typedef SPtr< BaiduProjection > BaiduProjectionPtr
typedef Byte< 3 > rgb
typedef GImage TinyMat
Enumerations
enum EstimatorMethod {
ITERATIVE = 0, FM_7POINT = 1, FM_8POINT = 2, LMEDS = 4,
RANSAC = 8
}
enum GElementType {
GElementType_8U =0, GElementType_8S =1, GElementType_16U =2, GElementType_16S =3,
GElementType_32S =4, GElementType_32F =5, GElementType_64F =6, GElementType_UserType =7
}
enum ImageChannelFlags {
IMAGE_UNDEFINED =0, IMAGE_RGBA =1<<0, IMAGE_BGRA =1<<1, IMAGE_GRAY =1<<2,
IMAGE_DEPTH =1<<3, IMAGE_IDEPTH =1<<4, IMAGE_RGBD =IMAGE_BGRA|IMAGE_DEPTH, IMAGE_GRE =1<<5,
IMAGE_NIR =1<<6, IMAGE_RED =1<<7, IMAGE_REG =1<<8, IMAGE_LIDAR =1<<9,
IMAGE_SONAR =1<<10, IMAGE_SAR =1<<11, IMAGE_THUMBNAIL =1<<12
}
enum CameraProjectionType { PROJECTION_PINHOLE, PROJECTION_SPHERE }
enum InvDepthEstimationDOF { UPDATE_ID_NONE = 0, UPDATE_ID_IDEPTH = 1, UPDATE_ID_SIGMA = 2, UPDATE_ID_IDEPTHSIGMA = UPDATE_ID_IDEPTH | UPDATE_ID_SIGMA }
enum KeyFrameEstimzationDOF {
UPDATE_KF_NONE = 0, UPDATE_KF_X = 1, UPDATE_KF_Y = 2, UPDATE_KF_Z = 4,
UPDATE_KF_RX = 8, UPDATE_KF_RY = 16, UPDATE_KF_RZ = 32, UPDATE_KF_SCALE = 64,
UPDATE_KF_TRANSLATION = UPDATE_KF_X | UPDATE_KF_Y | UPDATE_KF_Z, UPDATE_KF_XYZ = UPDATE_KF_TRANSLATION, UPDATE_KF_ROTATION = UPDATE_KF_RX | UPDATE_KF_RY | UPDATE_KF_RZ, UPDATE_KF_SE3 = UPDATE_KF_TRANSLATION | UPDATE_KF_ROTATION,
UPDATE_KF_SIM3 = UPDATE_KF_SE3 | UPDATE_KF_SCALE
}
enum CameraEstimationDOF {
UPDATE_CAMERA_NONE = 0, UPDATE_CAMERA_FOCAL = 1, UPDATE_CAMERA_CENTER = 2, UPDATE_CAMERA_K1 = 4,
UPDATE_CAMERA_K2 = 8, UPDATE_CAMERA_P1 = 16, UPDATE_CAMERA_P2 = 32, UPDATE_CAMERA_K3 = 64,
UPDATE_CAMERA_K = UPDATE_CAMERA_K1 | UPDATE_CAMERA_K2 | UPDATE_CAMERA_K3, UPDATE_CAMERA_P = UPDATE_CAMERA_P1 | UPDATE_CAMERA_P2, UPDATE_CAMERA_KP = UPDATE_CAMERA_K | UPDATE_CAMERA_P, UPDATE_CAMERA_PINHOLE = UPDATE_CAMERA_FOCAL | UPDATE_CAMERA_CENTER,
UPDATE_CAMERA_FISHEYE = UPDATE_CAMERA_PINHOLE | UPDATE_CAMERA_KP
}
Functions
REG_EVENT (CommandEvent, std::string, cmd)
REG_EVENT (ScenceCenterEvent, Point3d, center)
REG_EVENT (ScenceRadiusEvent, double, radius)
REG_EVENT (SetViewPoseEvent, SE3, pose)
REG_EVENT (CurrentFrameEvent, FramePtr, frame)
REG_EVENT2 (DrawableEvent, GObjectPtr, obj, std::string, name)
REG_EVENT2 (DebugImageEvent, GImage, img, std::string, name)
void get_timeinfo (struct tm &ti)
int64_t GetTID ()
std::set< LogSink * > & getLogSinksGlobal ()
void InitGoogleLogging (char *argv)
void AddLogSink (LogSink *sink)
void RemoveLogSink (LogSink *sink)
LogSinkMap & getLogSinkMapGlobal ()
void SetLogDestination (LogSeverity severity, const char *base_filename)
template<typename T >
T Square (T x)
double D2R (double degree)
double R2D (double radian)
void buildInHandle (void *ptr, std::string command, std::string sParams)
void systemFunction (void *ptr, std::string, std::string sParams)
template<class T >
T min (const T &v1, const T &v2)
template<class T >
T max (const T &v1, const T &v2)
std::string unitsFormat (const double val, int nDecimalDigits, bool middle_space)
std::string rightPad (const std::string &str, const size_t total_len, bool truncate_if_larger)
std::string aux_format_string_multilines (const std::string &s, const size_t len)
class __SCORING_CLASS (L1Scoring, true, Vocabulary::L1)
class __SCORING_CLASS (L2Scoring, true, Vocabulary::L2)
class __SCORING_CLASS (ChiSquareScoring, true, Vocabulary::L1)
class __SCORING_CLASS (KLScoring, true, Vocabulary::L1)
class __SCORING_CLASS (BhattacharyyaScoring, true, Vocabulary::L1)
class __SCORING_CLASS (DotProductScoring, false, Vocabulary::L1)
std::ostream & operator<< (std::ostream &os, const Vocabulary &voc)
Variables
const int GLOG_INFO = 0
const int GLOG_WARNING = 1
const int GLOG_ERROR = 2
const int GLOG_FATAL = 3
const int NUM_SEVERITIES = 4
const char *const LogSeverityNames [NUM_SEVERITIES]
static const double WGS84_A = 6378137.0
static const double WGS84_B = 6356752.314245
static const double WGS84_E = 0.0818191908
Detailed Description
The VideoFrame classes are used as the input of different slam systems Class name : "Frame"+MainSonsor+OtherSensor MainSonsor : Mono,Stereo,RGBD,Multi,Lidar OtherSensor: GPS,IMU,Compass.
Enumeration Type Documentation
enum EstimatorMethod
Enumerator
FM_7POINT
7-point algorithm
FM_8POINT
8-point algorithm
LMEDS
least-median algorithm
RANSAC
RANSAC algorithm.
Function Documentation
std::ostream& GSLAM::operator<< (std::ostream & os, const Vocabulary & voc)
Writes printable information of the vocabulary.
Parameters
os stream to write to
voc
References Vocabulary::getBranchingFactor(), Vocabulary::getDepthLevels(), Vocabulary::getScoringType(), Vocabulary::getWeightingType(), and Vocabulary::size().
Variable Documentation
const char* const LogSeverityNames[NUM_SEVERITIES]
Initial value:
= {
  "INFO", "WARNING", "ERROR", "FATAL"
}